@startuml


participant "Attested Account" as ATTE
participant "Verifier" as VERI


ATTE -> ATTE: create data object
note right
    dataObject: {
        payload: <data to be signed>
        attestationContext: <attestation context>
        attestationPath: [<attestor accounts up to root>]
        creatorAccount: <data object creator account>
        signature: <signature token created by data object creator account>
    }
end note


...
ATTE -> VERI: share data object

@enduml
