/*
 *  Copyright (C) 2019  Attila Aldemir <a_aldemir@hotmail.de>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */ 
 
@startuml


participant "Attestor Account\n(ARDOR-\n1111-1111-1111-11111)" as ATTE
participant "New Attestor Account\n(ARDOR-\n2222-2222-2222-22222)" as NATTE


== Self Attestation ==

ATTE -> ATTE: set account property
note right
    accountProperty: {
        property: ap://<attestation context>,
        value: 200|r|a|0000-0000-0000-00000|<account payload>
    }
end note
|||


...
== Account Deactivation ==

ATTE -> ATTE: update account property
note right
    accountProperty: {
        property: myAttestationContext,
        value: 200|r|i|0000-0000-0000-00000|<account payload>
    }
end note
|||


...
== Account Reactivation ==

ATTE -> ATTE: update account property
note right
    accountProperty: {
        property: myAttestationContext,
        value: 200|r|a|0000-0000-0000-00000|<account payload>
    }
end note
|||


...
== Account Payload Update ==

ATTE -> ATTE: update account property
note right
    accountProperty: {
        property: ap://<attestation context>,
        value: 200|r|a|0000-0000-0000-00000|<new account payload>
    }
end note


...
== Account Update ==

ATTE -> NATTE: set account property
note right
    accountProperty: {
        property: ap://<attestation context>,
        value: 200|r|a|0000-0000-0000-00000|<new account payload>
    }
end note


ATTE -> ATTE: update account property
note right
    accountProperty: {
        property: ap://<attestation context>,
        value: 200|r|d|2222-2222-2222-22222|<new account payload>
    }
end note
|||


...
== Attestation Revocation ==

NATTE -> NATTE: delete account property
|||


@enduml